[package]
name = "trade_match"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.11"
serde = {version = "1.0.144", features = ["derive"]}
thiserror = "1.0.34"
